// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA47irG3GL1NAb6K2SldIBt84C8hzX79FE',
    appId: '1:115161125408:web:b8cbd545588b0c3f6fe245',
    messagingSenderId: '115161125408',
    projectId: 'hajo-9983c',
    authDomain: 'hajo-9983c.firebaseapp.com',
    storageBucket: 'hajo-9983c.appspot.com',
    measurementId: 'G-TG60GBH4TV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuaAVsbar7QScTbzbDwsgldKZ5AYeueM0',
    appId: '1:115161125408:android:f0f7483bdc3755a66fe245',
    messagingSenderId: '115161125408',
    projectId: 'hajo-9983c',
    storageBucket: 'hajo-9983c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHcCDq9KSPccdCFXE8eGA6dkmkw5nrIG8',
    appId: '1:115161125408:ios:f0ad8b03cbc9e0d86fe245',
    messagingSenderId: '115161125408',
    projectId: 'hajo-9983c',
    storageBucket: 'hajo-9983c.appspot.com',
    iosClientId: '115161125408-f9h00d5vlufsp9dotmh5dhrpmhm9q1q2.apps.googleusercontent.com',
    iosBundleId: 'com.example.udharKharcha',
  );
}
